replicaCount: 1

app:
  profile: dev

image:
  repository: order-service
  tag: "dev-1"
  pullPolicy: IfNotPresent

imagePullSecrets: []

service:
  name: order-service
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  className: alb
  annotations: {}
  host: ""
